### ISSUE TITLE
App is crashing in iPhone 8

### ISSUE THREAD

**Issue by dishasyno** [JakeShelley1/SmileTracker#1]
i am using iPhone 8 with OS 12.2 but app is crashing on launch "ARKit is not supported".
<img width="856" alt="Screenshot 2019-05-07 at 6 13 07 PM" src="https://user-images.githubusercontent.com/37284799/57300140-cd957a00-70f3-11e9-9ba8-b58cf2ed19d5.png">

**Comment by JakeShelley1** [comment]
Just to confirm - Are you using a real device? The simulator doesn't support ARKit.

**Comment by dishasyno** [comment]
Hello

Yes I am using real device.

Thank you,

**Comment by JakeShelley1** [comment]
Cool thanks. I'll look into this a bit more when I get home later tonight. I'm limited to testing with an iPhoneX, but maybe I can find some answer as to why it wouldn't work on an iPhone 8.

For now, if possible, can you try to download another test and/or real app that uses ARKit to see if it works? You could also start a new Xcode project, import ARKit, and add the faceTrackingSupported check in viewDidLoad to see if it runs.

**Comment by dishasyno** [comment]
I have created a new project and tested, it is giving me same fatal error. I'll try in iPhone X if possible but please try to help with iPhone 8 because as per my knowledge after iPhone 6 ARKit is supported in all devices.

**Comment by JakeShelley1** [comment]
Hi Dishasyno - Unfortunately, the app won't run on iPhone 8, you'll need an iPhoneX or newer. In order to use ARFaceTrackingConfiguration you need a TrueDepth camera, which only the iPhoneX has at the moment. Sorry about the confusion.

**Comment by dishasyno** [comment]
okay JakeShelley. Thank you for quick response.
